# -*- coding: utf-8 -*-
"""Assignment DAY 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KzcShG9hKOX_Ru0IyyIejh2zCUBL34Eo
"""

import csv
import os


class Book:
    def __init__(self, book_id, title, author, category):
        self.book_id = book_id
        self.title = title
        self.author = author
        self.category = category
        self.available = True

    def display_book(self):
        status = "Available" if self.available else "Issued"

        print(f"ID: {self.book_id}")
        print(f"Title: {self.title}")
        print(f"Author: {self.author}")
        print(f"Category: {self.category}")
        print(f"Status: {status}")
        print("------------------------")


class Library:
    def __init__(self):
        self.books = []
        self.members = set()
        self.load_books()

    def add_book(self):
        book_id = input("Enter Book ID: ")

        for book in self.books:
            if book.book_id == book_id:
                print("Book ID already exists.")
                return

        title = input("Enter Book Title: ")
        author = input("Enter Author Name: ")
        category = input("Enter Category: ")

        book = Book(book_id, title, author, category)
        self.books.append(book)

        self.save_books()
        print("Book added successfully.")

    def view_books(self):
        if not self.books:
            print("No books available in the library.")
            return

        print("\n===== Library Books =====")

        for book in self.books:
            book.display_book()

    def search_book(self):
        search = input("Enter book title or author: ").lower()
        found = False

        for book in self.books:
            if (search in book.title.lower() or
                    search in book.author.lower()):

                book.display_book()
                found = True

        if not found:
            print("No matching book found.")

    def issue_book(self):
        book_id = input("Enter Book ID to issue: ")

        for book in self.books:
            if book.book_id == book_id:

                if not book.available:
                    print("This book is already issued.")
                    return

                member = input("Enter member name: ")

                self.members.add(member)
                book.available = False

                self.save_books()
                print(f"Book issued successfully to {member}.")
                return

        print("Book not found.")

    def return_book(self):
        book_id = input("Enter Book ID to return: ")

        for book in self.books:
            if book.book_id == book_id:

                if book.available:
                    print("This book is already available.")
                    return

                book.available = True
                self.save_books()

                print("Book returned successfully.")
                return

        print("Book not found.")

    def delete_book(self):
        book_id = input("Enter Book ID to delete: ")

        for book in self.books:
            if book.book_id == book_id:

                if not book.available:
                    print("Cannot delete a book that is currently issued.")
                    return

                self.books.remove(book)
                self.save_books()

                print("Book deleted successfully.")
                return

        print("Book not found.")

    def show_members(self):
        if not self.members:
            print("No members have borrowed books yet.")
            return

        print("\n===== Library Members =====")

        for member in self.members:
            print(member)

    def save_books(self):
        with open("books.csv", "w", newline="") as file:
            writer = csv.writer(file)

            writer.writerow(
                ["Book ID", "Title", "Author", "Category", "Available"]
            )

            for book in self.books:
                writer.writerow([
                    book.book_id,
                    book.title,
                    book.author,
                    book.category,
                    book.available
                ])

    def load_books(self):
        if not os.path.exists("books.csv"):
            return

        try:
            with open("books.csv", "r", newline="") as file:
                reader = csv.DictReader(file)

                for row in reader:
                    book = Book(
                        row["Book ID"],
                        row["Title"],
                        row["Author"],
                        row["Category"]
                    )

                    book.available = row["Available"] == "True"
                    self.books.append(book)

        except Exception:
            print("There was a problem loading the book data.")


def main():
    library = Library()

    while True:
        print("\n===== LIBRARY MANAGEMENT SYSTEM =====")
        print("1. Add Book")
        print("2. View All Books")
        print("3. Search Book")
        print("4. Issue Book")
        print("5. Return Book")
        print("6. Delete Book")
        print("7. View Members")
        print("8. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            library.add_book()

        elif choice == "2":
            library.view_books()

        elif choice == "3":
            library.search_book()

        elif choice == "4":
            library.issue_book()

        elif choice == "5":
            library.return_book()

        elif choice == "6":
            library.delete_book()

        elif choice == "7":
            library.show_members()

        elif choice == "8":
            print("Thank you for using the Library Management System!")
            break

        else:
            print("Invalid choice. Please try again.")


main()