# -*- coding: utf-8 -*-
"""Assignment DAY 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10I5zMUktN68rDbeeP_tL81-KTmjfJ3Az
"""

import numpy as np

# 1. Creating Arrays

array_1d = np.array([10, 20, 30, 40, 50])

array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D Array:")
print(array_1d)

print("\n2D Array:")
print(array_2d)

print("\n3D Array:")
print(array_3d)


# 2. Checking Dimensions and Data Types

print("\nNumber of dimensions:")
print("1D:", array_1d.ndim)
print("2D:", array_2d.ndim)
print("3D:", array_3d.ndim)

print("\nData type:", array_1d.dtype)
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)


# 3. Indexing

print("\nIndexing:")
print("First element:", array_1d[0])
print("Third element:", array_1d[2])
print("2D array element:", array_2d[1, 2])
print("3D array element:", array_3d[1, 0, 1])


# 4. Slicing

print("\nSlicing:")
print("First three elements:", array_1d[:3])
print("Last two elements:", array_1d[-2:])

print("\nFirst two rows of 2D array:")
print(array_2d[:2])

print("\nFirst two columns of 2D array:")
print(array_2d[:, :2])


# 5. Reshaping

numbers = np.arange(1, 13)

print("\nOriginal array:")
print(numbers)

reshaped_array = numbers.reshape(3, 4)

print("\nReshaped array:")
print(reshaped_array)


# 6. Creating Arrays Using NumPy Functions

zero_array = np.zeros((3, 3))
print("\nZeros:")
print(zero_array)

one_array = np.ones((2, 4))
print("\nOnes:")
print(one_array)

range_array = np.arange(1, 11)
print("\nArange:")
print(range_array)

linear_array = np.linspace(0, 10, 5)
print("\nLinspace:")
print(linear_array)


# 7. Mathematical Operations

numbers = np.array([10, 20, 30, 40, 50])

print("\nMathematical Operations:")
print("Addition:", numbers + 5)
print("Subtraction:", numbers - 5)
print("Multiplication:", numbers * 2)
print("Division:", numbers / 2)
print("Square:", numbers ** 2)


# 8. Vectorized Operations

marks = np.array([65, 72, 80, 55, 90])

new_marks = marks + 5

print("\nOriginal marks:", marks)
print("Marks after adding 5:", new_marks)


# 9. Boolean Masking

marks = np.array([45, 67, 82, 39, 91, 55, 76])

passed_marks = marks[marks >= 50]
high_marks = marks[marks > 75]

print("\nAll marks:", marks)
print("Passed marks:", passed_marks)
print("Marks above 75:", high_marks)


# 10. Broadcasting

prices = np.array([100, 200, 300, 400])

tax = 10
final_prices = prices + (prices * tax / 100)

print("\nOriginal prices:", prices)
print("Prices after 10% tax:", final_prices)

marks = np.array([
    [70, 80, 90],
    [60, 75, 85]
])

extra_marks = np.array([5, 5, 5])
new_marks = marks + extra_marks

print("\nOriginal marks:")
print(marks)

print("\nMarks after adding 5:")
print(new_marks)


# 11. Aggregate Functions

numbers = np.array([10, 20, 30, 40, 50])

print("\nAggregate Functions:")
print("Sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Minimum:", np.min(numbers))
print("Maximum:", np.max(numbers))
print("Median:", np.median(numbers))


# 12. Aggregate Functions on 2D Array

marks = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [65, 95, 88]
])

print("\n2D Marks:")
print(marks)

print("\nTotal:", np.sum(marks))
print("Average:", np.mean(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
print("Median:", np.median(marks))

print("\nRow-wise sum:")
print(np.sum(marks, axis=1))

print("\nColumn-wise sum:")
print(np.sum(marks, axis=0))

print("\nColumn-wise average:")
print(np.mean(marks, axis=0))


# 13. Simple Numerical Data Analysis

student_marks = np.array([78, 65, 89, 92, 56, 74, 81, 68, 95, 60])

print("\nStudent Marks:")
print(student_marks)

print("\nTotal Marks:", np.sum(student_marks))
print("Average Marks:", np.mean(student_marks))
print("Highest Mark:", np.max(student_marks))
print("Lowest Mark:", np.min(student_marks))
print("Median Mark:", np.median(student_marks))

passed = student_marks[student_marks >= 50]

print("\nNumber of students passed:", len(passed))
print("Passed Marks:", passed)