# -*- coding: utf-8 -*-
"""Assignment Day 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1enavu2LO5GFo8GozKe4CCm9Qm13gs7yU
"""

import csv
import os

file_name = "expenses.csv"


def add_expense():
    date = input("Enter date (DD-MM-YYYY): ")
    category = input("Enter expense category: ")

    try:
        amount = float(input("Enter amount: "))

        if amount <= 0:
            print("Amount should be greater than 0.")
            return

    except ValueError:
        print("Please enter a valid amount.")
        return

    note = input("Enter a note (optional): ")

    file_exists = os.path.exists(file_name)

    with open(file_name, "a", newline="") as file:
        writer = csv.writer(file)

        if not file_exists:
            writer.writerow(["Date", "Category", "Amount", "Note"])

        writer.writerow([date, category, amount, note])

    print("Expense added successfully.")


def view_expenses():
    if not os.path.exists(file_name):
        print("No expenses recorded yet.")
        return

    total_amount = 0

    print("\n--- All Expenses ---")

    with open(file_name, "r", newline="") as file:
        reader = csv.DictReader(file)

        for expense in reader:
            print(
                f"Date: {expense['Date']} | "
                f"Category: {expense['Category']} | "
                f"Amount: ₹{expense['Amount']} | "
                f"Note: {expense['Note']}"
            )

            total_amount += float(expense["Amount"])

    print("--------------------")
    print(f"Total Amount Spent: ₹{total_amount:.2f}")


def category_summary():
    if not os.path.exists(file_name):
        print("No expenses recorded yet.")
        return

    category_total = {}

    with open(file_name, "r", newline="") as file:
        reader = csv.DictReader(file)

        for expense in reader:
            category = expense["Category"]
            amount = float(expense["Amount"])

            if category in category_total:
                category_total[category] += amount
            else:
                category_total[category] = amount

    print("\n--- Category Wise Summary ---")

    for category, amount in category_total.items():
        print(f"{category}: ₹{amount:.2f}")


# Main menu
while True:
    print("\n===== Expense Tracker =====")
    print("1. Add Expense")
    print("2. View Expenses")
    print("3. Category Wise Summary")
    print("4. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        add_expense()

    elif choice == "2":
        view_expenses()

    elif choice == "3":
        category_summary()

    elif choice == "4":
        print("Thank you for using the Expense Tracker!")
        break

    else:
        print("Invalid choice. Please select a valid option.")